name: Install Docker

on:
  push:
   branches:
     - 'main'

jobs:
 install-docker: 
  runs on: ubuntu-latest

  steps:
    - name: Install Docker
      run: |
       sudo apt-get update -y
       sudo apt-get install -y docker.io

    - name: Check docker
     run: docker --version
      
       


   
