name: Java CI pipeline
on:
 workflow_dispatch

jobs:
 install-maven:
  runs-on: ubuntu-latest

  steps:
    - name: Install Maven
      run: |
       sudo apt-get update -y
       sudo apt-get install -y maven

    - name: Check Maven
      run: |
       mvn --version
  
    
