name: Java CI pipeline

on:
 push:
  branches:
    - 'main'

jobs:
 install-maven:
  runs-on: ubuntu-latest

  steps:
    - name: Install Maven
      run: |
       sudo apt-get update -y
       sudo apt-get install -y maven

    - name: Check Maven
      run: |
       mvn --version
  
   steps: 
    - name: Install Git
      run: |
       sudo apt-get git
      
   
