name: Java CI pipeline

on:
 push:
  branches:
    - 'main'

jobs:
 install-maven:
  runs-on: ubuntu-latest

  steps:
    - name: Install Maven
      run: |
       sudo apt-get update -y
       sudo apt-get install -y maven
       sudo apt-get install -y git
       
     - name: Install Apache2
       run: |
        sudo apt-get update -y
        sudo apt-get install -y apache2

    - name: Check Maven
      run: |
       mvn --version
       apache2 -v

      
   
